services:
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app/src
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_HOST=postgres
      - DB_NAME=teste_sigaa
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: teste_sigaa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: